name: MLOps - CI/CD pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: |
          pytest

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLECLOUD_JSON }}'
          PROJECT_ID: '${{ secrets.PROJECT_ID }}'
          service_account_key: '${{ secrets.SERVICE_ACCOUNT }}'
          export_default_credentials: true
      
      - name: Build the container image and push Artifact Registry
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/mlops/fastapi:latest .
          docker push us-central1-docker.pkg.dev/${PROJECT_ID}/mlops/fastapi:latest

      - name: Deploy To Cloud Run
        uses: google-github-actions/auth@v1
        with:
          service: fastapi
          image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/mlops/fastapi:latest
          region: us-central1
          allow-unauthenticated: true
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLECLOUD_JSON }} 
          # MLOps - CI/CD pipeline Github Actions
 
